apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-express
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo-express
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo-express
    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Release.Name }}-mongodb-service