apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-express-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mongo-express
  type: {{ .Values.mongoExpress.service.type }}
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081