apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongo.secret.username | b64enc }}
  mongo-root-password: {{ .Values.mongo.secret.password | b64enc }}